version: "3"
services:
  jibjib-api:
    image: "gunni1/plan-api:1.0.0"
    container_name: "plan-api"
    environment:
      - PLAN_DB_URL=mongodb://mongodb:27017
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - mongodb

  mongodb:
    image: mongo:3.6.11
    restart: always
    container_name: mongodb
    volumes:
      - "./db/data:/data/db"
      - "./db/conf:/etc/mongo"
    ports:
      - "27017:27017"