package api

const (
	ERR_NO_PLAN_FOUND         = "NO_PLAN_FOUND"
	ERR_INVALID_PLAN_ID       = "INVALID_PLAN_ID"
	ERR_NO_FAVORITES_FOR_USER = "NO_FAVORITES_FOR_USER"
	ERR_FAVORITE_NOT_FOUND    = "FAVORITE_NOT_FOUND"
	ERR_TITLE_ALREADY_EXISTS  = "TITLE_ALREADY_EXISTS"
)
